#!/usr/bin/env bash
# vim: set tabstop=4 expandtab shiftwidth=4 bg=dark:
# vim: set textwidth=80:
#==============================================================================
#
# File        : git-id
# Description : manage Git user identities for the current session
#
# Copyright (c) 2015, Kilian Cavalotti <kilian@stanford.edu>
#
# Licensed under the GNU General Public License, v2
#==============================================================================


# -- environment setup --------------------------------------------------------
# check if the current script has been sourced or executed
[[ "$0" != "$BASH_SOURCE" ]] && gitid_sourced=1 || gitid_sourced=0
# get script name and path
gitid_path=$(readlink -m ${BASH_SOURCE[0]})
gitid_name=${gitid_path##*/}


# -- functions ----------------------------------------------------------------

# this function is exported in the user environment and embeds all available
# actions
git-id() {

    usage() {
        cat << EOU
$gitid_name: manage Git user identities

Actions: add        add a new identity, or update an existing one
         delete     remove an existing identity
         list       list existing identities
         show       show identity info
         current    display current identity
         use        use the selected identity
         reset      unset the environment, reset to the default id
         help       this message

Usage: $gitid_name add    <username> <full name> <email> <s:sshkey>|<t:token>
       $gitid_name delete <username>
       $gitid_name list
       $gitid_name show   <username>
       $gitid_name current
       $gitid_name use    <username>
       $gitid_name reset
       $gitid_name help

Notes:
   1. a path to a SSH private key *or* an access token can be provided, but not
      both, they're mutually exclusive.
   2. The type of credential should be indicated with the "s:" (for SSH key) or
      "t:" (for token) prefix.
   3. when invoked without any parameters, git-id acts as a command to use in
      GIT_SSH and/or GIT_ASKPASS

EOU
        return 0
    }

    ## git functions ----------------------------------------------------------

    # sanity check: verify that Git is installed, and that we can access a
    # repo's local git config
    git_sanity_check() {
        type git &>/dev/null || {
            echo "Really? Git is not even installed?"
            return 1
        }

        git rev-parse --show-toplevel &>/dev/null || {
            echo "The current directory doesn't seem to be part of a Git repo."
            return 1
        }
    }

    # lookup key in gitconfig identity namespace
    # @input    $1: identity
    #           $2: key (name, email...)
    # @output   value
    lookup() {
        local id="$1"
        local key="$2"

        git config -z "identity.$id.$key"
    }

    ## actions ----------------------------------------------------------------

    # add a new (or update an exiting) identity to the list of identities for
    # the current repository
    # @input    $1: identity
    #           $2: full name (quoted if needed)
    #           $3: email address
    #           $4: path to the SSH key to be used with that id, *OR*
    #               access token
    # @output:  status message
    add_id() {
        local id="$1"
        local name="$2"
        local email="$3"
        local cred="$4"

        # check if id already exists
        lookup $id name &>/dev/null \
            && actioned="updated" \
            || actioned="created"

        # check if cred is a file (sshkey) or not (token)
        case ${cred%:*} in
            s)  sshkey=${cred#*:}
                ;;
            t)  token=${cred#*:}
                ;;
            *)  echo "error: invalid credential type (should be s: or t:)"
                return 1
                ;;
        esac

        # check if $sshkey is a valid private key
        [[ -n ${sshkey:-} ]] && {
            head -n1 "$sshkey" |& grep -q "PRIVATE KEY" || {
                mesg="error: $sshkey doesn't appear to be a valid "
                mesg+="SSH private key."
                echo "$mesg"
                return 1
            }
        }

        # store the identity in the local git config
        {   git config identity."$id".name "$name"
            git config identity."$id".email "$email"
            [[ -n ${sshkey:-} ]] && git config identity."$id".sshkey "$sshkey"
            [[ -n ${token:-} ]]  && git config identity."$id".token "$token"
        } && echo "success: identity $id $actioned."
    }

    # remove an identity from the list of identities for the current repository
    # @input    $1: identity
    # @output   status message
    remove_id() {
        local id="$1"

        # check if id already exists
        lookup $id name &>/dev/null || {
            echo "error: identity $id does not exist."
            return 1
        }

        git config --remove-section identity."$id" \
            && echo "success: identity $id removed."
    }

    # list existing identities for the current repository
    # @input    n/a
    # @output   sorted list of identities
    list_ids() {
        git config --get-regexp ^identity\. | cut -d. -f2 | sort -u
    }

    # display identity details
    # @input    $1: identity
    # @output   id name, email, sshkey, token
    show_id() {
        local id="$1"

        # check if id exists
        lookup $id name &>/dev/null || {
            echo "$id is not defined"
            return 1
        }

        local   name="$(lookup $id name)"
        local  email="$(lookup $id email)"
        local sshkey="$(lookup $id sshkey)"
        local  token="$(lookup $id token)"

        [[ "$name" == "" ]] && {
            echo "error: id doesn't exist"
            return 1
        }

        echo "[$id]"
        echo "   name: $name"
        echo "  email: $email"
        [[ -n ${sshkey:-} ]] && echo "ssh key: ${sshkey:-}" || true
        [[ -n ${token:-} ]]  && echo "  token: ${token:-}"  || true
    }

    # set environment to use specific identity
    # @input    $1: identity
    # @output:  status message
    use_id() {
        local id=$1

        # check if id exists
        lookup $id name &>/dev/null || {
            echo "$id is not defined"
            return 1
        }

        # get id details
        local   name="$(lookup $id name)"
        local  email="$(lookup $id email)"
        local sshkey="$(lookup $id sshkey)"
        local  token="$(lookup $id token)"

        # check if identity already set
        [[ -n $GIT_ID ]] && \
            echo "switching Git id from $GIT_ID to $id" || \
            echo "using identity: $id"

        # set the environment
        export GIT_ID="$id"
        export GIT_AUTHOR_NAME="$name"
        export GIT_AUTHOR_EMAIL="$email"
        export GIT_COMMITTER_NAME="$name"
        export GIT_COMMITTER_EMAIL="$email"

        # set GIT_SSH to this very script if we have a ssh key
        [[ -n ${sshkey:-} ]] && {
            export GIT_SSH=$gitid_path
        }
        # set GIT_ASKPASS to this very script if we have a token
        [[ -n ${token:-} ]]  && {
            export GIT_ASKPASS=$gitid_path
        }
    }

    # list existing identities for the current repository
    # @input    n/a
    # @output   sorted list of identities
    list_ids() {
        git config --get-regexp ^identity\. | cut -d. -f2 | sort -u
    }

    # read current identitiy from the environment
    # @input    n/a
    # @output   current identity
    current_id() {
        local id=$GIT_ID

        [[ $id == "" ]] && {
            echo "error: identity not set"
            return 1
        } || echo "$id"
    }

    # reset environment
    # @input    n/a
    # @output   status message
    reset() {
        # unset variables
        unset GIT_ID
        unset GIT_AUTHOR_NAME
        unset GIT_AUTHOR_EMAIL
        unset GIT_COMMITTER_NAME
        unset GIT_COMMITTER_EMAIL
        unset GIT_SSH
        echo "environment unset"
    }

    # function called when the script is executed (not sourced) and used from
    # the GIT_SSH env variable. Used to specify different SSH key when
    # pulling/pushing to Git remotes.
    # Directly executed by Git, so no input/output interaction
    # Needs to return 0, otherwise git may receive a SIGPIPE and display errors
    # like "failed to push some refs"
    git_ssh() {
        local id=$GIT_ID

        ssh -i $(lookup $id sshkey) $@
        exit 0
    }

    # function called when the script is executed (not sourced) and used from
    # the GIT_ASKPASS env variable. Used to provide username and password
    # pulling/pushing to Git remotes.
    # Directly executed by Git, so no input/output interaction
    # Needs to return 0, otherwise git may receive a SIGPIPE and display errors
    # like "failed to push some refs"
    # @input    $1: "Username" or "Password"
    # @output   requested information
    git_askpass() {
        local action=$1
        local id=$GIT_ID

        case $action in
            Username) echo $id ;;
            Password) lookup $id token ;;
        esac
        exit 0
    }


    # -- main -----------------------------------------------------------------

    # get action from the command line arguments
    action="${1:-}"

    git_sanity_check || return 1

    case $action in
        add)
            shift
            [[ $# == 4 ]] || {
                usage
                return 1
            } && add_id "$1" "$2" "$3" "$4"
            ;;
        delete|remove)
            shift
            [[ $# == 1 ]] && \
                remove_id "$1" || {
                usage
                return 1
            }
            ;;
        list)
            list_ids
            ;;
        show)
            shift
            if [[ $# == 1 ]]; then
                show_id "$1"
            else
                usage
                return 1
            fi
            ;;
        current)
            current_id
            ;;
        use)
            shift
            [[ $# == 1 ]] && {
                [[ $gitid_sourced == 1 ]] || {
                    echo -n "error: identity cannot be set by executing the "
                    echo -n "script directly, you need to source the script "
                    echo "and call the function instead ('git-id use $1')"
                    return 1
                }
                use_id "$1" || return 1
            } || {
                usage
                return 1
            }
            ;;
        reset)
            reset
            return 1
            ;;
        Username*|Password*)
            # getting a Username/Password prompt means we're being used as
            # GIT_ASKPASS, return username and token
            git_askpass $action
            ;;
        *@*|*.*)
            # anything like user@host.tld means we're being used as GIT_SSH
            git_ssh $@
            ;;
        help|*)
            usage
            return 1
            ;;
    esac

}

# -- excution entry point -----------------------------------------------------

# if executed directly, pass the arguments to the correct function
[[ $gitid_sourced == 0 ]] &&
    git-id $@

## returns if script is sourced, or exits if it's executed
return 2>/dev/null || exit
